spring.application.name=logistica

# Puerto del microservicio
server.port=8083

# RabbitMQ
spring.rabbitmq.host=rabbitmq-service
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-service:5432/logistica
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true